// react-todo/src/components/AddTodo.js
import React, { Component } from 'react';

export class AddTodo extends Component {
    //This is a component level state
    state = {
        title: ''
    }

    onChange = (e) => this.setState({ [e.target.name]: e.target.value });

    onSubmit = (e) => {
        e.preventDefault();
        this.props.addTodo(this.state.title);
        this.setState({ title: '' })
    }

    render() {
    return (
      <form className='main-form' onSubmit={this.onSubmit}>
        <input
            type='text' 
            name='title' 
            placeholder='Add Todo..'
            value={this.state.title}
            onChange={this.onChange}
        />
        <input 
            type='submit' 
            value='Add Item'
            className='btn-submit' 
            placeholder='Add Todo..'
        />       
      </form>
    );
  }
}

export default AddTodo;

// vue-todo/src/components/AddTodo.vue
<template>
    <div>
        <form @submit="addTodo">
            <input type="text" v-model="title" name="title" placeholder="Add Todo...">
            <input type="submit" value="Submit" class="btn">
        </form>
    </div>
</template>

<script>
//import uuid from 'uuid';

export default {
    name: "AddTodo",
    data() {
        return{
            title: ''
        }
    },
    methods: {
        addTodo(e) {
            e.preventDefault();
            const newTodo = {
                //id: uuid.v4(),
                title: this.title,
                completed: false
            }
            //send up to parent
            this.$emit('add-todo', newTodo);
            this.title = '';
        }
    }
}
</script>

<style scoped>
    form{
        display: flex;
    }

    input[type="text"]{
        flex: 10;
        padding: 5px;
    }

    input[type="submit"]{
        flex: 2;
    }
</style>
